name: Build Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Compile firmware
      run: |
        chmod +x compile-with-docker.sh
        ./compile-with-docker.sh

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware-artifact
        path: compiled-firmware/f4hwn.packed.bin

    - name: Comment PR with download link
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const run_id = context.runId;
          const repo = context.repo;

          const comment = `🚀 **Firmware Build Completed!**

          📦 Download the compiled firmware: [f4hwn.packed.bin](https://github.com/${repo.owner}/${repo.repo}/actions/runs/${run_id})

          Click the link above, then download the \`firmware-artifact\` from the artifacts section.`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: repo.owner,
            repo: repo.repo,
            body: comment
          });